Added some stories
standardebooks/robert-e-howard_short-fiction pull request #8
Opened 2024-07-03 23:39 UTC by HendrikBK

Added the following stories to the book:
The Lost Race
The Dream Snake
The Hyena
The Shadow Kingdom
The Mirrors of Tuzun Thune
Rattle of Bones
Skull-Face
Skulls in the Stars
The Haunter of the Ring
The Grisly Horror
The Fire of Ashurbanipal
Black Hound of Death
Black Canaan
Dig Me no Grave

2024-07-09 16:40 UTC, acabal requested changes
Thanks Hendrik. There's a note about CSS and also, all ordinals must be Roman numerals. Can you please convert all ordinals in this PR and add the `z3998:roman` semantic? Then the ToC will have to be updated.

2024-07-09 16:40 UTC, acabal commented on src/epub/css/local.css
> +[epub|type~="z3998:letter"] header + p{
This has no effect, you can remove it

2024-07-09 16:40 UTC, acabal commented on src/epub/css/local.css
> +[epub|type~="z3998:letter"] header + p{
`[epub|type~="z3998:letter"] header + p`

2024-07-09 16:42 UTC, acabal commented
Also, something is broken in one of the filenames. `se lint` fails with a file not found error. Please fix that and make sure `se build --check-only` succeeds too.

2024-07-09 23:49 UTC, HendrikBK commented
I think I fixed all issues. The issue with the file name was that I modernized _Ashurbanipal_ but forgot to change the file-name.

2024-07-10 15:54 UTC, acabal commented
OK, looks good, thanks!

2024-07-10 15:54 UTC, merged